# Generated by Django 4.2.15 on 2024-08-19 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDistributionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_email', models.EmailField(max_length=254)),
                ('distribution_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=100)),
                ('incident_summary', models.TextField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('impact_start_time_utc', models.DateTimeField()),
                ('impact_end_time_utc', models.DateTimeField()),
                ('impact_duration', models.DurationField(default=None)),
                ('previous_business_impact', models.TextField()),
                ('current_business_impact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_priority', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=150)),
                ('market_abbreviation', models.CharField(max_length=50)),
                ('market_timezone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SystemServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_service_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ITSMService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ITSM_name', models.CharField(max_length=150)),
                ('market_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident_management.market')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.service')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_description', models.TextField()),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incident_management.incident')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='incident',
            name='ITSMService_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.itsmservice'),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.incidentpriority'),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.incidentstatus'),
        ),
        migrations.AddField(
            model_name='incident',
            name='market_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.market'),
        ),
        migrations.AddField(
            model_name='incident',
            name='service_impacted_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.systemservices'),
        ),
    ]
