# Generated by Django 4.2.15 on 2024-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='current_business_impact',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='incident',
            name='impact_end_time_utc',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='incident',
            name='previous_business_impact',
            field=models.TextField(default=None),
        ),
    ]
