# Generated by Django 5.0.4 on 2024-08-12 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.incidentstatus'),
        ),
    ]
