# Generated by Django 5.0.4 on 2024-08-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0002_incident_incident_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_priority', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='incidentupdate',
            name='incident_status_id',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='incident_management.incidentpriority'),
        ),
    ]
