# Generated by Django 4.2.15 on 2024-08-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_management', '0002_alter_incident_current_business_impact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
